-- MySQL Script generated by MySQL Workbench
-- mar. 31 oct. 2017 10:10:50 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instruments` (
  `Models` VARCHAR(50) NULL,
  `ID_Violoncelle` VARCHAR(45) NOT NULL,
  `ID_Guitare` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Guitare`, `ID_Violoncelle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produits` (
  `ID_produits` VARCHAR(45) NOT NULL,
  `ID_Guitare` VARCHAR(45) NULL,
  `ID_Violoncelle` VARCHAR(45) NULL,
  `Marque` VARCHAR(45) NULL,
  `Categorie` VARCHAR(45) NULL,
  `Bois_utilise` VARCHAR(45) NULL,
  `Description` VARCHAR(500) NULL,
  `instruments_ID_Guitare` VARCHAR(45) NOT NULL,
  `instruments_ID_Violoncelle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_produits`),
  INDEX `fk_produits_instruments1_idx` (`instruments_ID_Guitare` ASC, `instruments_ID_Violoncelle` ASC),
  CONSTRAINT `fk_produits_instruments1`
    FOREIGN KEY (`instruments_ID_Guitare` , `instruments_ID_Violoncelle`)
    REFERENCES `mydb`.`instruments` (`ID_Guitare` , `ID_Violoncelle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
